// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillChallenge.Data;

#nullable disable

namespace SkillChallenge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521121505_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillChallenge.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SkillChallenge.Models.Challenge", b =>
                {
                    b.Property<int>("ChallengeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChallengeId"));

                    b.Property<string>("ChallengeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimePeriod")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UnderCategoryId")
                        .HasColumnType("int");

                    b.HasKey("ChallengeId");

                    b.HasIndex("UnderCategoryId");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("SkillChallenge.Models.UnderCategory", b =>
                {
                    b.Property<int>("UnderCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnderCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UnderCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnderCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("UnderCategories");
                });

            modelBuilder.Entity("SkillChallenge.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("ChallengeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillChallenge.Models.Challenge", b =>
                {
                    b.HasOne("SkillChallenge.Models.UnderCategory", "UnderCategory")
                        .WithMany()
                        .HasForeignKey("UnderCategoryId");

                    b.Navigation("UnderCategory");
                });

            modelBuilder.Entity("SkillChallenge.Models.UnderCategory", b =>
                {
                    b.HasOne("SkillChallenge.Models.Category", "Category")
                        .WithMany("UnderCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SkillChallenge.Models.User", b =>
                {
                    b.HasOne("SkillChallenge.Models.Challenge", null)
                        .WithMany("Users")
                        .HasForeignKey("ChallengeId");
                });

            modelBuilder.Entity("SkillChallenge.Models.Category", b =>
                {
                    b.Navigation("UnderCategories");
                });

            modelBuilder.Entity("SkillChallenge.Models.Challenge", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
