name: Build and Deploy SkillChallenge to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore SkillChallenge.sln

      # Build
      - name: Build
        run: dotnet build SkillChallenge.sln --configuration Release --no-restore

      # Publish (create folder for deployment)
      - name: Publish
        run: dotnet publish SkillChallenge/SkillChallenge.csproj -c Release -o ./publish

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: skillchallenge   # <-- change if your Azure Web App has a different name
          slot-name: production
          package: ./publish
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
