# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET with Csharpier Format Check

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore tools
        working-directory: SkillChallenge
        run: dotnet tool restore

      - name: Check formatting with Csharpier
        working-directory: SkillChallenge
        run: dotnet csharpier check .

      - name: Restore dependencies
        run: dotnet restore SkillChallenge.sln

      - name: Build
        run: dotnet build SkillChallenge.sln --no-restore

      - name: Run Tests
        run: dotnet test SkillChallenge.sln --no-build --verbosity normal
        env:
          ASPNETCORE_ENVIRONMENT: CI
